on:
  push:
    branches:
      - dev

permissions:
  contents: read

concurrency:
  group: frontend-ci-push-merged-ktb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: 이미지 빌드 검증
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
